AllCops:
  NewCops: disable
  SuggestExtensions: false

Metrics/MethodLength:
  Max: 50
  Enabled: false

Metrics/AbcSize:
  Max: 40
  Enabled: false

Metrics/BlockLength:
  Max: 50
  Exclude:
    - 'Rakefile'
    - '**/*.rake'
    - 'spec/**/*.rb'
  Enabled: false

Metrics/CyclomaticComplexity:
  Enabled: false

Metrics/PerceivedComplexity:
  Enabled: false

Metrics/BlockNesting:
  Enabled: false

Metrics/ClassLength:
  Enabled: false

Metrics/ParameterLists:
  Enabled: false

Metrics/ModuleLength:
  Enabled: false

Style/EvalWithLocation:
  Enabled: false

Style/Documentation:
  Enabled: false

Style/FrozenStringLiteralComment:
  Enabled: false

Style/SafeNavigation:
  Enabled: false

Layout/FirstArrayElementIndentation:
  Enabled: false

Layout/CommentIndentation:
  Enabled: false

Style/PerlBackrefs:
  Enabled: false

Style/RegexpLiteral:
  Enabled: false

Style/PercentLiteralDelimiters:
  Enabled: false

Layout/LineLength:
  Enabled: false

Style/GlobalVars:
  Enabled: false

Lint/UnderscorePrefixedVariableName:
  Enabled: false

Style/NumericPredicate:
  Exclude:
    - 'lib/job2sh.rb'
    - 'lib/matrix.rb'
    - 'lib/stats.rb'

Security/Eval:
  Enabled: false

Security/JSONLoad:
  Enabled: false

Layout/HeredocIndentation:
  Enabled: false

# Disable this temporarily to let rubocop 1.12.1 work with ruby3.2
Layout/BlockAlignment:
  Enabled: false

Lint/ShadowingOuterLocalVariable:
  Enabled: false

Style/MissingRespondToMissing:
  Enabled: false

Security/YAMLLoad:
  Enabled: false

Style/FormatStringToken:
  Enabled: false

Style/FloatDivision:
  Exclude:
    - 'programs/pmbench/parse'

Naming/AccessorMethodName:
  Exclude:
    - 'lib/compare.rb'
    - 'lib/data_store.rb'
    - 'lib/nresult_root.rb'
    - 'lib/property.rb'
    - 'lib/result_root.rb'

Naming/MethodParameterName:
  Enabled: false

Naming/HeredocDelimiterNaming:
  Enabled: false

